from typing import Dict, List
from abc import ABC, abstractmethod

class BaseWearableClient(ABC):
    @abstractmethod
    async def get_daily_summary(self) -> Dict: ...
    @abstractmethod
    async def get_heart_rate_realtime(self) -> Dict: ...
    @abstractmethod
    async def get_sleep_data(self) -> Dict: ...
    @abstractmethod
    async def get_activity_sessions(self) -> List: ...
    @abstractmethod
    async def sync(self) -> Dict: ...
